# Generated by Django 5.1.7 on 2025-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctor_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Rapor/Dosya'),
        ),
    ]
